version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-blog}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
    volumes:
      - database_data:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-root}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-pass}
    ports:
      - "8080:80"
    links:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  phpmyadmin_data:
